angular.module("ljaWebHomePage",[
	"ngRoute",
	"ngMessages",
	"contenteditable",
	"controllers.HomePage",
	"directives.navgps",
	"directives.jobList",
	"controllers.jobList",
	"controllers.joinus",
	"controllers.test",
	"services.common"
])
.config(function(
	$routeProvider,
	$locationProvider
){   
	$routeProvider
		.when("/",{
			templateUrl:"template/Home-page.html",
			controller:"HomePage"
		}).when("/join",{
			templateUrl:"template/joinus.html",
			controller:"joinus"
		}).when("/test",{
			templateUrl:"template/test.html",
			controller:"test"
		})
	 $locationProvider.html5Mode(true);
}) 