angular.module("ljaWebDriveSchool",[
	"ngRoute",
	"ngMessages",
	"controllers.login",
	"controllers.split",
	"controllers.signalcoach",
	"controllers.addMuch",
	"controllers.stutent",
	"controllers.good",
	// "controllers.getbad",
	"controllers.addAllStu",
	"controllers.getstudent",
	"controllers.getcoach",
	"directives.allStudent",
	"directives.bindCar",
	"directives.login",
	"directives.forall",
    "directives.goodItem",
	"directives.coachTemp",
	"directives.studentTemp",
	"directives.newInput",
	"directives.errorList",
	"directives.newOnput",
	"directives.muchcoach",
	"services.common"
])
.config(function(
	$routeProvider,
	$locationProvider
){ 
	$routeProvider
		.when("/login",{
			templateUrl:"template/login.html",
			controller:"Login"
		}).when("/addsignal",{
			templateUrl:"template/signalcoach.html",
			controller:"signalcoach"
		}).when("/addmuch",{
			templateUrl:"template/muchcoach.html",
			controller:"addMuch"
		}).when("/split",{
			templateUrl:"template/split.html",
			controller:"split"
		}).when("/addStutent",{
			templateUrl:"template/student.html",
			controller:"stutent"
		}).when("/addAllStu",{
			templateUrl:"template/allStudent.html",
			controller:"addAllStu"
		}).when("/addAllCars",{
			templateUrl:"template/coachcars.html",
			controller:"coachcars"
		}).when("/getGoodNews",{
			templateUrl:"template/good.html",
			controller:"good"
		}).when("/getcoach",{
			templateUrl:"template/getcoach.html",
			controller:"getcoach"
		}).when("/getstudent",{
			templateUrl:"template/getstudent.html",
			controller:"getstudent"
		}).when("/getBadNews",{
			templateUrl:"template/getBadNews.html",
			controller:"getbad"
		})
	 $locationProvider.html5Mode(true);
})