angular.module("ljaWebDriveSchool",[
	"ngRoute",
	"ngMessages",
	"controllers.login",
	"controllers.split",
	"controllers.signalcoach",
	"controllers.addMuch",
	"controllers.stutent",
	"controllers.addAllStu",
    "controllers.coachcars",
	"directives.allStudent",
	"directives.coachcars",
	"directives.login",
	"directives.muchcoach",
	"services.common"
])
.config(function(
	$routeProvider,
	$locationProvider
){ 
	$routeProvider
		.when("/login",{
			templateUrl:"template/login.html",
			controller:"Login"
		}).when("/addsignal",{
			templateUrl:"template/signalcoach.html",
			controller:"signalcoach"
		}).when("/addmuch",{
			templateUrl:"template/muchcoach.html",
			controller:"addMuch"
		}).when("/split",{
			templateUrl:"template/split.html",
			controller:"split"
		}).when("/addStutent",{
			templateUrl:"template/student.html",
			controller:"stutent"
		}).when("/addAllStu",{
			templateUrl:"template/allStudent.html",
			controller:"addAllStu"
		}).when("/addAllCars",{
			templateUrl:"template/coachcars.html",
			controller:"coachcars"
		})
	 $locationProvider.html5Mode(true);
})