angular.module("ljaWebDriveSchool",[
	"ngRoute",
	"ngMessages",
	"controllers.login",
	"controllers.split",
	"controllers.signalcoach",
	"controllers.addMuch",
	"directives.login",
	"directives.muchcoach",
	"services.common"
])
.config(function(
	$routeProvider,
	$locationProvider
){ 
	$routeProvider
		.when("/login",{
			templateUrl:"template/login.html",
			controller:"Login"
		}).when("/addsignal",{
			templateUrl:"template/signalcoach.html",
			controller:"signalcoach"
		}).when("/addmuch",{
			templateUrl:"template/muchcoach.html",
			controller:"addMuch"
		}).when("/split",{
			templateUrl:"template/split.html",
			controller:"split"
		})
	 $locationProvider.html5Mode(true);
})